import type { Metadata } from "next";
import "./globals.css";
import { Sora } from "next/font/google";

// Initialisation de la police Sora
const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "700"], // Ajouter les variantes nécessaires
  variable: "--font-sora", // Variable CSS personnalisée
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.variable}>
        {children}
      </body>
    </html>
  );
}
