coursInformatique = [
    "Introduction à l'informatique",
    "Algorithmique et structures de données",
    "Programmation en C",
    "Programmation en Java",
    "Programmation en Python",
    "Développement Web Front-End (HTML, CSS, JavaScript)",
    "Développement Web Back-End (Node.js, PHP, Python)",
    "Bases de données SQL (MySQL, PostgreSQL)",
    "Bases de données NoSQL (MongoDB, Cassandra)",
    "Réseaux informatiques et protocoles",
    "Sécurité informatique et cryptographie",
    "Systèmes d'exploitation (Linux, Windows)",
    "Architecture des ordinateurs",
    "Intelligence artificielle (IA)",
    "Machine Learning (ML)",
    "Deep Learning (DL)",
    "Cloud Computing (AWS, Azure, GCP)",
    "DevOps et automatisation",
    "Gestion de projet informatique",
    "Test logiciel et assurance qualité (QA)",
    "Développement mobile (Android, iOS)",
    "Internet des Objets (IoT)",
    "Big Data et Hadoop",
    "Cybersécurité offensive (Pentesting)",
    "Cybersécurité défensive (SIEM)",
    "Conception d'interfaces utilisateur (UI/UX)",
    "Théorie des langages et compilation",
    "Calculabilité et complexité",
    "Logique et fondements de l'informatique",
    "Traitement du signal et image",
    "Vision par ordinateur",
    "Robotique et automatisation",
    "Bioinformatique et biologie computationnelle",
    "Informatique quantique",
    "Réalité virtuelle et augmentée (VR/AR)",
    "Blockchain et cryptomonnaies",
      "Éthique de l'informatique et droit du numérique",
      "Intelligence d'affaires (BI)",
      "Science des données",
      "Analyse de données",
      "Visualisation de données",
      "Marketing numérique et SEO",
      "Gestion des systèmes d'information (SI)",
      "Méthodes agiles (Scrum, Kanban)",
      "Gestion de la configuration",
      "Intégration continue et déploiement continu (CI/CD)",
      "Sécurité des applications web",
      "Sécurité des réseaux sans fil",
      "Informatique embarquée",
      "Systèmes distribués",
      "Programmation concurrente et parallèle",
      "Optimisation algorithmique",
      "Génie logiciel",
      "Management de l'innovation technologique",
      "Droit de l'informatique et des nouvelles technologies",
      "Protection des données personnelles (RGPD)",
      "Audit informatique",
      "Informatique forensique",
      "Sécurité physique des infrastructures",
      "Gestion des risques informatiques",
      "Continuité d'activité et reprise après sinistre",
      "Virtualisation et conteneurisation avancées",
      "Infrastructure as Code (IaC)",
      "Serverless computing",
      "Edge computing",
      "Intelligence artificielle explicable (XAI)",
      "Traitement automatique du langage naturel (TALN)",
      "Apprentissage par renforcement",
      "Informatique graphique et modélisation 3D",
      "Jeux vidéo et développement de jeux",
      "Interaction homme-machine (IHM)",
      "Accessibilité web",
      "Cloud hybride et multi-cloud",
      "Sécurité du cloud",
      "Gouvernance des données",
      "Qualité des données",
      "Architecture orientée services (SOA)",
      "API et microservices",
      "Intégration d'applications d'entreprise (EAI)",
      "Transformation digitale",
      "Stratégie informatique",
      "Urbanisation des systèmes d'information",
      "Veille technologique",
      "Gestion des connaissances",
      "Gestion de l'information",
      "Bibliothèques et frameworks JavaScript avancés (React, Angular, Vue.js)",
      "Tests unitaires et tests d'intégration",
      "Débogage et profilage",
      "Performance web et optimisation",
      "Accessibilité numérique",
      "Localisation et internationalisation",
      "Sécurité des applications mobiles",
      "Déploiement et maintenance d'applications mobiles",
      "Tendances émergentes en informatique"
  ];
  categoriesInformatiques = [
    "Programmation et développement logiciel",
    "Bases de données",
    "Réseaux informatiques",
    "Sécurité informatique (Cybersécurité)",
    "Intelligence artificielle (IA)",
    "Systèmes d'exploitation",
    "Architecture des ordinateurs",
    "Cloud Computing",
    "DevOps",
    "Internet des Objets (IoT)",
    "Informatique graphique et infographie",
    "Science des Données (Data Science)",
    "Gestion de Projet Informatique",
      "Informatique Théorique"
  ];
  
module.exports = { coursInformatique, categoriesInformatiques };